apiVersion: v1
kind: Pod
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  containers:
    - name: order-service
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80